
package com.akmozo.ejb.imp;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.akmozo.ejb.api.Devise;
import com.akmozo.ejb.api.ObjectFactory;
import com.akmozo.ejb.api.Pays;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IServiceDevise", targetNamespace = "http://api.ejb.app.akmozo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IServiceDevise {


    /**
     * 
     * @param codeDevise
     * @return
     *     returns com.akmozo.app.ejb.api.Devise
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDevise", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetDevise")
    @ResponseWrapper(localName = "getDeviseResponse", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetDeviseResponse")
    public Devise getDevise(
        @WebParam(name = "codeDevise", targetNamespace = "")
        String codeDevise);

    /**
     * 
     * @param in
     * @param montant
     * @param out
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.ConvertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant,
        @WebParam(name = "in", targetNamespace = "")
        String in,
        @WebParam(name = "out", targetNamespace = "")
        String out);

    /**
     * 
     * @param devise
     * @return
     *     returns java.util.List<com.akmozo.app.ejb.api.Pays>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPaysByDevise", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetPaysByDevise")
    @ResponseWrapper(localName = "getPaysByDeviseResponse", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetPaysByDeviseResponse")
    public List<Pays> getPaysByDevise(
        @WebParam(name = "devise", targetNamespace = "")
        Devise devise);

    /**
     * 
     * @param devise
     * @return
     *     returns com.akmozo.app.ejb.api.Devise
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDevise", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.AddDevise")
    @ResponseWrapper(localName = "addDeviseResponse", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.AddDeviseResponse")
    public Devise addDevise(
        @WebParam(name = "devise", targetNamespace = "")
        Devise devise);

    /**
     * 
     * @param codeDevise
     * @return
     *     returns java.util.List<com.akmozo.app.ejb.api.Pays>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPaysByDeviseCode", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetPaysByDeviseCode")
    @ResponseWrapper(localName = "getPaysByDeviseCodeResponse", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetPaysByDeviseCodeResponse")
    public List<Pays> getPaysByDeviseCode(
        @WebParam(name = "codeDevise", targetNamespace = "")
        String codeDevise);

    /**
     * 
     * @return
     *     returns java.util.List<com.akmozo.app.ejb.api.Devise>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDevises", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetDevises")
    @ResponseWrapper(localName = "getDevisesResponse", targetNamespace = "http://api.ejb.app.akmozo.com/", className = "com.akmozo.app.ejb.api.GetDevisesResponse")
    public List<Devise> getDevises();

}
